controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

erpag_security:
    resource: "@ErpagUserBundle/Resources/config/routing.yml"
    prefix:   /